# Generated by Django 5.1.7 on 2025-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
