# Generated by Django 5.1.7 on 2025-03-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0002_userwaterintake_email_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
