# Generated by Django 5.1.7 on 2025-03-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0003_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegoal',
            name='total_water_drink',
            field=models.FloatField(default=0),
        ),
    ]
