# Generated by Django 5.1.7 on 2025-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0004_savegoal_total_water_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwaterintake',
            name='reminder_times',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userwaterintake',
            name='email_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=50),
        ),
    ]
