# Generated by Django 5.1.7 on 2025-03-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0005_userwaterintake_reminder_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwaterintake',
            name='email_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=50, null=True),
        ),
    ]
